// Code generated by reset. DO NOT EDIT.
package repository

func (rs *Consumer) Reset() {
	if rs == nil {
		return
	}

}

func (rs *gauge) Reset() {
	if rs == nil {
		return
	}

	rs.Name = ""
	rs.Value = 0
}
