// Code generated by reset. DO NOT EDIT.
package agent

func (rs *Task) Reset() {
	if rs == nil {
		return
	}

	rs.ID = ""
	rs.URL = ""
	rs.Method = ""
	rs.Body = rs.Body[:0]
	clear(rs.Headers)
	rs.Attempts = 0
	if resetter, ok := interface{}(&rs.Timeout).(interface{ Reset() }); ok {
		resetter.Reset()
	}
	rs.Result = nil
	rs.Error = nil
}
